export function getCityPhotos(cityName: string) {
  switch (cityName) {
    case "Bruges":
      return photos.Bruges;
    case "Brussels":
      return photos.Brussels;
    case "Anderlecht":
      return photos.Anderlecht;
    case "Barcelona":
      return photos.Barcelona;
    default:
      return [];
  }
}

export const photos = {
  Barcelona: [
    {
      original: "Barcelona/1.jpg",
      thumbnail: "Barcelona/1.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Barcelona/2.jpg",
      thumbnail: "Barcelona/2.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/3.jpg",
      thumbnail: "Barcelona/3.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/4.jpg",
      thumbnail: "Barcelona/4.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/5.jpg",
      thumbnail: "Barcelona/5.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/6.jpg",
      thumbnail: "Barcelona/6.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/7.jpg",
      thumbnail: "Barcelona/7.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/8.jpg",
      thumbnail: "Barcelona/8.jpg",
      alt: "",
      width: 1366,
      height: 562,
    },
    {
      original: "Barcelona/9.jpg",
      thumbnail: "Barcelona/9.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/10.jpg",
      thumbnail: "Barcelona/10.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/11.jpg",
      thumbnail: "Barcelona/11.jpg",
      alt: "",
      width: 1366,
      height: 451,
    },
    {
      original: "Barcelona/12.jpg",
      thumbnail: "Barcelona/12.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/13.jpg",
      thumbnail: "Barcelona/13.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/14.jpg",
      thumbnail: "Barcelona/14.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/15.jpg",
      thumbnail: "Barcelona/15.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/16.jpg",
      thumbnail: "Barcelona/16.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/17.jpg",
      thumbnail: "Barcelona/17.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/18.jpg",
      thumbnail: "Barcelona/18.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/19.jpg",
      thumbnail: "Barcelona/19.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/20.jpg",
      thumbnail: "Barcelona/20.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/21.jpg",
      thumbnail: "Barcelona/21.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/22.jpg",
      thumbnail: "Barcelona/22.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/23.jpg",
      thumbnail: "Barcelona/23.jpg",
      alt: "",
      width: 1365,
      height: 768,
    },
    {
      original: "Barcelona/24.jpg",
      thumbnail: "Barcelona/24.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/25.jpg",
      thumbnail: "Barcelona/25.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/26.jpg",
      thumbnail: "Barcelona/26.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/27.jpg",
      thumbnail: "Barcelona/27.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/28.jpg",
      thumbnail: "Barcelona/28.jpg",
      alt: "",
      width: 1366,
      height: 333,
    },
    {
      original: "Barcelona/29.jpg",
      thumbnail: "Barcelona/29.jpg",
      alt: "",
      width: 1366,
      height: 327,
    },
    {
      original: "Barcelona/30.jpg",
      thumbnail: "Barcelona/30.jpg",
      alt: "",
      width: 1366,
      height: 317,
    },
    {
      original: "Barcelona/31.jpg",
      thumbnail: "Barcelona/31.jpg",
      alt: "",
      width: 1366,
      height: 303,
    },
    {
      original: "Barcelona/32.jpg",
      thumbnail: "Barcelona/32.jpg",
      alt: "",
      width: 1366,
      height: 382,
    },
    {
      original: "Barcelona/33.jpg",
      thumbnail: "Barcelona/33.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/34.jpg",
      thumbnail: "Barcelona/34.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/35.jpg",
      thumbnail: "Barcelona/35.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/36.jpg",
      thumbnail: "Barcelona/36.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Barcelona/37.jpg",
      thumbnail: "Barcelona/37.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/38.jpg",
      thumbnail: "Barcelona/38.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Barcelona/39.jpg",
      thumbnail: "Barcelona/39.jpg",
      alt: "",
      width: 1366,
      height: 260,
    },
    {
      original: "Barcelona/40.jpg",
      thumbnail: "Barcelona/49.jpg",
      alt: "",
      width: 686,
      height: 915,
    },
    {
      original: "Barcelona/41.jpg",
      thumbnail: "Barcelona/41.jpg",
      alt: "",
      width: 735,
      height: 980,
    },
    {
      original: "Barcelona/42.jpg",
      thumbnail: "Barcelona/42.jpg",
      alt: "",
      width: 860,
      height: 688,
    },
    {
      original: "Barcelona/43.jpg",
      thumbnail: "Barcelona/43.jpg",
      alt: "",
      width: 750,
      height: 1000,
    },
    {
      original: "Barcelona/44.jpg",
      thumbnail: "Barcelona/44.jpg",
      alt: "",
      width: 735,
      height: 980,
    },
    {
      original: "Barcelona/45.jpg",
      thumbnail: "Barcelona/45.jpg",
      alt: "",
      width: 733,
      height: 977,
    },
    {
      original: "Barcelona/46.jpg",
      thumbnail: "Barcelona/46.jpg",
      alt: "",
      width: 707,
      height: 942,
    },
    {
      original: "Barcelona/47.jpg",
      thumbnail: "Barcelona/47.jpg",
      alt: "",
      width: 726,
      height: 967,
    },
    {
      original: "Barcelona/48.jpg",
      thumbnail: "Barcelona/48.jpg",
      alt: "",
      width: 656,
      height: 875,
    },
    {
      original: "Barcelona/49.jpg",
      thumbnail: "Barcelona/49.jpg",
      alt: "",
      width: 724,
      height: 966,
    },
    {
      original: "Barcelona/50.jpg",
      thumbnail: "Barcelona/50.jpg",
      alt: "",
      width: 735,
      height: 980,
    },
    {
      original: "Barcelona/51.jpg",
      thumbnail: "Barcelona/51.jpg",
      alt: "",
      width: 742,
      height: 594,
    },
    {
      original: "Barcelona/52.jpg",
      thumbnail: "Barcelona/52.jpg",
      alt: "",
      width: 1001,
      height: 751,
    },
    {
      original: "Barcelona/53.jpg",
      thumbnail: "Barcelona/53.jpg",
      alt: "",
      width: 988,
      height: 741,
    },
    {
      original: "Barcelona/54.jpg",
      thumbnail: "Barcelona/54.jpg",
      alt: "",
      width: 932,
      height: 699,
    },
    {
      original: "Barcelona/55.jpg",
      thumbnail: "Barcelona/55.jpg",
      alt: "",
      width: 1080,
      height: 810,
    },
    {
      original: "Barcelona/56.jpg",
      thumbnail: "Barcelona/56.jpg",
      alt: "",
      width: 899,
      height: 1123,
    },
  ],
  Anderlecht: [
    {
      original: "Anderlecht/1.jpg",
      thumbnail: "Anderlecht/1_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Anderlecht/2.jpg",
      thumbnail: "Anderlecht/2_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Anderlecht/3.jpg",
      thumbnail: "Anderlecht/3_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Anderlecht/4.jpg",
      thumbnail: "Anderlecht/4_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Anderlecht/5.mp4",
      thumbnail: "Anderlecht/5_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
      video: true,
    },
    {
      original: "Anderlecht/6.jpg",
      thumbnail: "Anderlecht/6_thumb.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Anderlecht/7.mp4",
      thumbnail: "Anderlecht/7_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
      video: true,
    },
    {
      original: "Anderlecht/8.mp4",
      thumbnail: "Anderlecht/8_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
      video: true,
    },
    {
      original: "https://www.youtube.com/watch?v=_CaBMaSUx_w",
      thumbnail: "Anderlecht/9_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
      youtube: true,
    },
  ],
  Bruges: [
    {
      original: "Bruges/1.jpg",
      thumbnail: "Bruges/1_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Bruges/2.jpg",
      thumbnail: "Bruges/2_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Bruges/3.jpg",
      thumbnail: "Bruges/3_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Bruges/4.jpg",
      thumbnail: "Bruges/4_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Bruges/5.jpg",
      thumbnail: "Bruges/5_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Bruges/6.jpg",
      thumbnail: "Bruges/6_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Bruges/7.jpg",
      thumbnail: "Bruges/7_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Bruges/8.jpg",
      thumbnail: "Bruges/8_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Bruges/9.jpg",
      thumbnail: "Bruges/9_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Bruges/10.jpg",
      thumbnail: "Bruges/10_thumb.jpg",
      alt: "",
      width: 5,
      height: 4,
    },
    {
      original: "Bruges/11.jpg",
      thumbnail: "Bruges/11_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Bruges/12.jpg",
      thumbnail: "Bruges/12_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Bruges/13.jpg",
      thumbnail: "Bruges/13_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Bruges/14.jpg",
      thumbnail: "Bruges/14_thumb.jpg",
      alt: "",
      width: 4,
      height: 3,
    },
    {
      original: "Bruges/15.jpg",
      thumbnail: "Bruges/15_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Bruges/16.jpg",
      thumbnail: "Bruges/16_thumb.jpg",
      alt: "",
      width: 5,
      height: 4,
    },
  ],
  Brussels: [
    {
      original: "Brussels/1.jpg",
      thumbnail: "Brussels/1_thumb.jpg",
      alt: "A random road in Brussels",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/2.jpg",
      thumbnail: "Brussels/2_thumb.jpg",
      alt: "Brussels Parliament",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/3.jpg",
      thumbnail: "Brussels/3_thumb.jpg",
      alt: "",
      width: 3,
      height: 4,
    },
    {
      original: "Brussels/4.jpg",
      thumbnail: "Brussels/4_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/5.jpg",
      thumbnail: "Brussels/5_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/6.jpg",
      thumbnail: "Brussels/6_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/7.jpg",
      thumbnail: "Brussels/7_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/8.jpg",
      thumbnail: "Brussels/8_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/9.jpg",
      thumbnail: "Brussels/9_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/10.jpg",
      thumbnail: "Brussels/10_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/11.jpg",
      thumbnail: "Brussels/11_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/12.jpg",
      thumbnail: "Brussels/12_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/13.jpg",
      thumbnail: "Brussels/13_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/14.jpg",
      thumbnail: "Brussels/14_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/15.jpg",
      thumbnail: "Brussels/15_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/16.jpg",
      thumbnail: "Brussels/16_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/17.jpg",
      thumbnail: "Brussels/17_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/18.jpg",
      thumbnail: "Brussels/18_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/19.jpg",
      thumbnail: "Brussels/19_thumb.jpg",

      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/20.jpg",
      thumbnail: "Brussels/20_thumb.jpg",

      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/21.jpg",
      thumbnail: "Brussels/21_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/22.jpg",
      thumbnail: "Brussels/22_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/23.jpg",
      thumbnail: "Brussels/23_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/24.jpg",
      thumbnail: "Brussels/24_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/25.jpg",
      thumbnail: "Brussels/25_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/26.jpg",
      thumbnail: "Brussels/26_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/27.jpg",
      thumbnail: "Brussels/27_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/28.jpg",
      thumbnail: "Brussels/28_thumb.jpg",
      alt: "",
      width: 5,
      height: 4,
    },
    {
      original: "Brussels/29.jpg",
      thumbnail: "Brussels/29_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/30.jpg",
      thumbnail: "Brussels/30_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/31.jpg",
      thumbnail: "Brussels/31_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/32.jpg",
      thumbnail: "Brussels/32_thumb.jpg",
      alt: "",
      width: 5,
      height: 4,
    },
    {
      original: "Brussels/33.jpg",
      thumbnail: "Brussels/33_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/34.jpg",
      thumbnail: "Brussels/34_thumb.jpg",
      alt: "",
      width: 2,
      height: 3,
    },
    {
      original: "Brussels/35.jpg",
      thumbnail: "Brussels/35_thumb.jpg",
      alt: "",
      width: 13,
      height: 9,
    },
    {
      original: "Brussels/36.jpg",
      thumbnail: "Brussels/36_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/37.jpg",
      thumbnail: "Brussels/37_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/38.jpg",
      thumbnail: "Brussels/38_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/39.jpg",
      thumbnail: "Brussels/39_thumb.jpg",
      alt: "",
      width: 5,
      height: 4,
    },
    {
      original: "Brussels/40.jpg",
      thumbnail: "Brussels/49_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/41.jpg",
      thumbnail: "Brussels/41_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/42.jpg",
      thumbnail: "Brussels/42_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/43.jpg",
      thumbnail: "Brussels/43_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/44.jpg",
      thumbnail: "Brussels/44_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/45.jpg",
      thumbnail: "Brussels/45_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/46.jpg",
      thumbnail: "Brussels/46_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/47.jpg",
      thumbnail: "Brussels/47_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/48.jpg",
      thumbnail: "Brussels/48_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/49.jpg",
      thumbnail: "Brussels/49_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/50.jpg",
      thumbnail: "Brussels/50_thumb.jpg",
      alt: "",
      width: 3,
      height: 2,
    },
    {
      original: "Brussels/51.jpg",
      thumbnail: "Brussels/51_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/52.jpg",
      thumbnail: "Brussels/52_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/53.jpg",
      thumbnail: "Brussels/53_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/54.jpg",
      thumbnail: "Brussels/54_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/55.jpg",
      thumbnail: "Brussels/55_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/56.jpg",
      thumbnail: "Brussels/56_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/57.jpg",
      thumbnail: "Brussels/57_thumb.jpg",
      alt: "",
      width: 3,
      height: 2,
    },
    {
      original: "Brussels/58.jpg",
      thumbnail: "Brussels/58_thumb.jpg",
      alt: "",
      width: 3,
      height: 2,
    },
    {
      original: "Brussels/59.jpg",
      thumbnail: "Brussels/59_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/60.jpg",
      thumbnail: "Brussels/60_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/61.jpg",
      thumbnail: "Brussels/61_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/62.jpg",
      thumbnail: "Brussels/62_thumb.jpg",
      alt: "",
      width: 4,
      height: 5,
    },
    {
      original: "Brussels/63.jpg",
      thumbnail: "Brussels/63_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/64.jpg",
      thumbnail: "Brussels/64_thumb.jpg",
      alt: "",
      width: 2,
      height: 3,
    },
    {
      original: "Brussels/65.jpg",
      thumbnail: "Brussels/65_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/66.jpg",
      thumbnail: "Brussels/66_thumb.jpg",
      alt: "",
      width: 9,
      height: 16,
    },
    {
      original: "Brussels/67.jpg",
      thumbnail: "Brussels/67_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/68.jpg",
      thumbnail: "Brussels/68_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/69.jpg",
      thumbnail: "Brussels/69_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/70.jpg",
      thumbnail: "Brussels/70_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/71.jpg",
      thumbnail: "Brussels/71_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
    {
      original: "Brussels/72.jpg",
      thumbnail: "Brussels/72_thumb.jpg",
      alt: "",
      width: 16,
      height: 9,
    },
  ],
};
