export const barcellona = [
  {
    original: "Barcelona/1.jpg",
    thumbnail: "Barcelona/1.jpg",
    description: "A random road in Barcelona",
    alt: "",
    width: 16,
    height: 9,
  },
  {
    original: "Barcelona/2.jpg",
    thumbnail: "Barcelona/2.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/3.jpg",
    thumbnail: "Barcelona/3.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/4.jpg",
    thumbnail: "Barcelona/4.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/5.jpg",
    thumbnail: "Barcelona/5.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/6.jpg",
    thumbnail: "Barcelona/6.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/7.jpg",
    thumbnail: "Barcelona/7.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/8.jpg",
    thumbnail: "Barcelona/8.jpg",
    alt: "",
    width: 1366,
    height: 562,
  },
  {
    original: "Barcelona/9.jpg",
    thumbnail: "Barcelona/9.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/10.jpg",
    thumbnail: "Barcelona/10.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/11.jpg",
    thumbnail: "Barcelona/11.jpg",
    alt: "",
    width: 1366,
    height: 451,
  },
  {
    original: "Barcelona/12.jpg",
    thumbnail: "Barcelona/12.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/13.jpg",
    thumbnail: "Barcelona/13.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/14.jpg",
    thumbnail: "Barcelona/14.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/15.jpg",
    thumbnail: "Barcelona/15.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/16.jpg",
    thumbnail: "Barcelona/16.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/17.jpg",
    thumbnail: "Barcelona/17.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/18.jpg",
    thumbnail: "Barcelona/18.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/19.jpg",
    thumbnail: "Barcelona/19.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/20.jpg",
    thumbnail: "Barcelona/20.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/21.jpg",
    thumbnail: "Barcelona/21.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/22.jpg",
    thumbnail: "Barcelona/22.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/23.jpg",
    thumbnail: "Barcelona/23.jpg",
    alt: "",
    width: 1365,
    height: 768,
  },
  {
    original: "Barcelona/24.jpg",
    thumbnail: "Barcelona/24.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/25.jpg",
    thumbnail: "Barcelona/25.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/26.jpg",
    thumbnail: "Barcelona/26.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/27.jpg",
    thumbnail: "Barcelona/27.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/28.jpg",
    thumbnail: "Barcelona/28.jpg",
    alt: "",
    width: 1366,
    height: 333,
  },
  {
    original: "Barcelona/29.jpg",
    thumbnail: "Barcelona/29.jpg",
    alt: "",
    width: 1366,
    height: 327,
  },
  {
    original: "Barcelona/30.jpg",
    thumbnail: "Barcelona/30.jpg",
    alt: "",
    width: 1366,
    height: 317,
  },
  {
    original: "Barcelona/31.jpg",
    thumbnail: "Barcelona/31.jpg",
    alt: "",
    width: 1366,
    height: 303,
  },
  {
    original: "Barcelona/32.jpg",
    thumbnail: "Barcelona/32.jpg",
    alt: "",
    width: 1366,
    height: 382,
  },
  {
    original: "Barcelona/33.jpg",
    thumbnail: "Barcelona/33.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/34.jpg",
    thumbnail: "Barcelona/34.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/35.jpg",
    thumbnail: "Barcelona/35.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/36.jpg",
    thumbnail: "Barcelona/36.jpg",
    alt: "",
    width: 3,
    height: 4,
  },
  {
    original: "Barcelona/37.jpg",
    thumbnail: "Barcelona/37.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/38.jpg",
    thumbnail: "Barcelona/38.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Barcelona/39.jpg",
    thumbnail: "Barcelona/39.jpg",
    alt: "",
    width: 1366,
    height: 260,
  },
  {
    original: "Barcelona/40.jpg",
    thumbnail: "Barcelona/49.jpg",
    alt: "",
    width: 686,
    height: 915,
  },
  {
    original: "Barcelona/41.jpg",
    thumbnail: "Barcelona/41.jpg",
    alt: "",
    width: 735,
    height: 980,
  },
  {
    original: "Barcelona/42.jpg",
    thumbnail: "Barcelona/42.jpg",
    alt: "",
    width: 860,
    height: 688,
  },
  {
    original: "Barcelona/43.jpg",
    thumbnail: "Barcelona/43.jpg",
    alt: "",
    width: 750,
    height: 1000,
  },
  {
    original: "Barcelona/44.jpg",
    thumbnail: "Barcelona/44.jpg",
    alt: "",
    width: 735,
    height: 980,
  },
  {
    original: "Barcelona/45.jpg",
    thumbnail: "Barcelona/45.jpg",
    alt: "",
    width: 733,
    height: 977,
  },
  {
    original: "Barcelona/46.jpg",
    thumbnail: "Barcelona/46.jpg",
    alt: "",
    width: 707,
    height: 942,
  },
  {
    original: "Barcelona/47.jpg",
    thumbnail: "Barcelona/47.jpg",
    alt: "",
    width: 726,
    height: 967,
  },
  {
    original: "Barcelona/48.jpg",
    thumbnail: "Barcelona/48.jpg",
    alt: "",
    width: 656,
    height: 875,
  },
  {
    original: "Barcelona/49.jpg",
    thumbnail: "Barcelona/49.jpg",
    alt: "",
    width: 724,
    height: 966,
  },
  {
    original: "Barcelona/50.jpg",
    thumbnail: "Barcelona/50.jpg",
    alt: "",
    width: 735,
    height: 980,
  },
  {
    original: "Barcelona/51.jpg",
    thumbnail: "Barcelona/51.jpg",
    alt: "",
    width: 742,
    height: 594,
  },
  {
    original: "Barcelona/52.jpg",
    thumbnail: "Barcelona/52.jpg",
    alt: "",
    width: 1001,
    height: 751,
  },
  {
    original: "Barcelona/53.jpg",
    thumbnail: "Barcelona/53.jpg",
    alt: "",
    width: 988,
    height: 741,
  },
  {
    original: "Barcelona/54.jpg",
    thumbnail: "Barcelona/54.jpg",
    alt: "",
    width: 932,
    height: 699,
  },
  {
    original: "Barcelona/55.jpg",
    thumbnail: "Barcelona/55.jpg",
    alt: "",
    width: 1080,
    height: 810,
  },
  {
    original: "Barcelona/56.jpg",
    thumbnail: "Barcelona/56.jpg",
    alt: "",
    width: 899,
    height: 1123,
  },
];
