export const budapest = [
  {
    original: "Budapest/1.jpg",
    alt: "",
    thumbnail: "Budapest/1_thumb.jpg",
    width: 64,
    height: 85,
  },
  {
    original: "Budapest/2.jpg",
    alt: "",
    thumbnail: "Budapest/2_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/3.jpg",
    alt: "",
    thumbnail: "Budapest/3_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/4.jpg",
    alt: "",
    thumbnail: "Budapest/4_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/5.jpg",
    alt: "",
    thumbnail: "Budapest/5_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/6.jpg",
    alt: "",
    thumbnail: "Budapest/6_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/7.jpg",
    alt: "",
    thumbnail: "Budapest/7_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/8.jpg",
    alt: "",
    thumbnail: "Budapest/8_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/9.jpg",
    alt: "",
    thumbnail: "Budapest/9_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/10.jpg",
    alt: "",
    thumbnail: "Budapest/10_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/11.jpg",
    alt: "",
    thumbnail: "Budapest/11_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/12.jpg",
    alt: "",
    thumbnail: "Budapest/12_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/13.jpg",
    alt: "",
    thumbnail: "Budapest/13_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/14.mp4",
    alt: "",
    thumbnail: "Budapest/14_thumb.jpg",
    width: 9,
    height: 16,
    video: true,
  },
  {
    original: "Budapest/15.jpg",
    alt: "",
    thumbnail: "Budapest/15_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/16.jpg",
    alt: "",
    thumbnail: "Budapest/16_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/17.jpg",
    alt: "",
    thumbnail: "Budapest/17_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/18.jpg",
    alt: "",
    thumbnail: "Budapest/18_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/19.jpg",
    alt: "",
    thumbnail: "Budapest/19_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/20.jpg",
    alt: "",
    thumbnail: "Budapest/20_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/21.jpg",
    alt: "",
    thumbnail: "Budapest/21_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/22.jpg",
    alt: "",
    thumbnail: "Budapest/22_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/23.jpg",
    alt: "",
    thumbnail: "Budapest/23_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/24.jpg",
    alt: "",
    thumbnail: "Budapest/24_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/25.jpg",
    alt: "",
    thumbnail: "Budapest/25_thumb.jpg",
    width: 771,
    height: 1024,
  },
  {
    original: "Budapest/26.jpg",
    alt: "",
    thumbnail: "Budapest/26_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/27.jpg",
    alt: "",
    thumbnail: "Budapest/27_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/28.jpg",
    alt: "",
    thumbnail: "Budapest/28_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/29.jpg",
    alt: "",
    thumbnail: "Budapest/29_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/30.jpg",
    alt: "",
    thumbnail: "Budapest/30_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/31.jpg",
    alt: "",
    thumbnail: "Budapest/31_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/32.jpg",
    alt: "",
    thumbnail: "Budapest/32_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/33.jpg",
    alt: "",
    thumbnail: "Budapest/33_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/34.mp4",
    alt: "",
    thumbnail: "Budapest/34_thumb.jpg",
    width: 9,
    height: 16,
    video: true,
  },
  {
    original: "Budapest/35.jpg",
    alt: "",
    thumbnail: "Budapest/35_thumb.jpg",
    width: 64,
    height: 85,
  },
  {
    original: "Budapest/36.jpg",
    alt: "",
    thumbnail: "Budapest/36_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/37.jpg",
    alt: "",
    thumbnail: "Budapest/37_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/38.jpg",
    alt: "",
    thumbnail: "Budapest/38_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/39.jpg",
    alt: "",
    thumbnail: "Budapest/39_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/40.jpg",
    alt: "",
    thumbnail: "Budapest/40_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/41.jpg",
    alt: "",
    thumbnail: "Budapest/41_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/42.jpg",
    alt: "",
    thumbnail: "Budapest/42_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/43.jpg",
    alt: "",
    thumbnail: "Budapest/43_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/44.jpg",
    alt: "",
    thumbnail: "Budapest/44_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/45.jpg",
    alt: "",
    thumbnail: "Budapest/45_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/46.jpg",
    alt: "",
    thumbnail: "Budapest/46_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/47.jpg",
    alt: "",
    thumbnail: "Budapest/47_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/48.jpg",
    alt: "",
    thumbnail: "Budapest/48_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/49.jpg",
    alt: "",
    thumbnail: "Budapest/49_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/50.jpg",
    alt: "",
    thumbnail: "Budapest/50_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/51.jpg",
    alt: "",
    thumbnail: "Budapest/51_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/52.jpg",
    alt: "",
    thumbnail: "Budapest/52_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/53.jpg",
    alt: "",
    thumbnail: "Budapest/53_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/54.jpg",
    alt: "",
    thumbnail: "Budapest/54_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/55.jpg",
    alt: "",
    thumbnail: "Budapest/55_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/56.jpg",
    alt: "",
    thumbnail: "Budapest/56_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/57.jpg",
    alt: "",
    thumbnail: "Budapest/57_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/58.jpg",
    alt: "",
    thumbnail: "Budapest/58_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/59.jpg",
    alt: "",
    thumbnail: "Budapest/59_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/60.jpg",
    alt: "",
    thumbnail: "Budapest/60_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/61.jpg",
    alt: "",
    thumbnail: "Budapest/61_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/62.jpg",
    alt: "",
    thumbnail: "Budapest/62_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/63.jpg",
    alt: "",
    thumbnail: "Budapest/63_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/64.jpg",
    alt: "",
    thumbnail: "Budapest/64_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/65.jpg",
    alt: "",
    thumbnail: "Budapest/65_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/66.jpg",
    alt: "",
    thumbnail: "Budapest/66_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/67.jpg",
    alt: "",
    thumbnail: "Budapest/67_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/68.jpg",
    alt: "",
    thumbnail: "Budapest/68_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/69.jpg",
    alt: "",
    thumbnail: "Budapest/69_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/70.jpg",
    alt: "",
    thumbnail: "Budapest/70_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/71.jpg",
    alt: "",
    thumbnail: "Budapest/71_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/72.jpg",
    alt: "",
    thumbnail: "Budapest/72_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/73.jpg",
    alt: "",
    thumbnail: "Budapest/73_thumb.jpg",
    width: 64,
    height: 85,
  },
  {
    original: "Budapest/74.jpg",
    alt: "",
    thumbnail: "Budapest/74_thumb.jpg",
    width: 64,
    height: 85,
  },
  {
    original: "Budapest/75.jpg",
    alt: "",
    thumbnail: "Budapest/75_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/76.jpg",
    alt: "",
    thumbnail: "Budapest/76_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/77.jpg",
    alt: "",
    thumbnail: "Budapest/77_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/78.jpg",
    alt: "",
    thumbnail: "Budapest/78_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/79.jpg",
    alt: "",
    thumbnail: "Budapest/79_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/80.jpg",
    alt: "",
    thumbnail: "Budapest/80_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/81.jpg",
    alt: "",
    thumbnail: "Budapest/81_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/82.jpg",
    alt: "",
    thumbnail: "Budapest/82_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/83.jpg",
    alt: "",
    thumbnail: "Budapest/83_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/84.mp4",
    alt: "",
    thumbnail: "Budapest/84_thumb.jpg",
    width: 9,
    height: 16,
    video: true,
  },
  {
    original: "Budapest/85.jpg",
    alt: "",
    thumbnail: "Budapest/85_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/86.jpg",
    alt: "",
    thumbnail: "Budapest/86_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/87.jpg",
    alt: "",
    thumbnail: "Budapest/87_thumb.jpg",
    width: 1925,
    height: 811,
  },
  {
    original: "Budapest/88.jpg",
    alt: "",
    thumbnail: "Budapest/88_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/89.jpg",
    alt: "",
    thumbnail: "Budapest/89_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/90.jpg",
    alt: "",
    thumbnail: "Budapest/90_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/91.jpg",
    alt: "",
    thumbnail: "Budapest/91_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/92.jpg",
    alt: "",
    thumbnail: "Budapest/92_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/93.jpg",
    alt: "",
    thumbnail: "Budapest/93_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/94.jpg",
    alt: "",
    thumbnail: "Budapest/94_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/95.jpg",
    alt: "",
    thumbnail: "Budapest/95_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/96.jpg",
    alt: "",
    thumbnail: "Budapest/96_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/97.jpg",
    alt: "",
    thumbnail: "Budapest/97_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/98.jpg",
    alt: "",
    thumbnail: "Budapest/98_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/99.jpg",
    alt: "",
    thumbnail: "Budapest/99_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/100.jpg",
    alt: "",
    thumbnail: "Budapest/100_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/101.jpg",
    alt: "",
    thumbnail: "Budapest/101_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/102.jpg",
    alt: "",
    thumbnail: "Budapest/102_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/103.jpg",
    alt: "",
    thumbnail: "Budapest/103_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/104.jpg",
    alt: "",
    thumbnail: "Budapest/104_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/105.jpg",
    alt: "",
    thumbnail: "Budapest/105_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/106.jpg",
    alt: "",
    thumbnail: "Budapest/106_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/107.jpg",
    alt: "",
    thumbnail: "Budapest/107_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/108.jpg",
    alt: "",
    thumbnail: "Budapest/108_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/109.jpg",
    alt: "",
    thumbnail: "Budapest/109_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/110.jpg",
    alt: "",
    thumbnail: "Budapest/110_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/111.jpg",
    alt: "",
    thumbnail: "Budapest/111_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/112.jpg",
    alt: "",
    thumbnail: "Budapest/112_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/113.jpg",
    alt: "",
    thumbnail: "Budapest/113_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/114.jpg",
    alt: "",
    thumbnail: "Budapest/114_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/115.jpg",
    alt: "",
    thumbnail: "Budapest/115_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/116.jpg",
    alt: "",
    thumbnail: "Budapest/116_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/117.jpg",
    alt: "",
    thumbnail: "Budapest/117_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/118.jpg",
    alt: "",
    thumbnail: "Budapest/118_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/119.jpg",
    alt: "",
    thumbnail: "Budapest/119_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/120.jpg",
    alt: "",
    thumbnail: "Budapest/120_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/121.jpg",
    alt: "",
    thumbnail: "Budapest/121_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/122.jpg",
    alt: "",
    thumbnail: "Budapest/122_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/123.jpg",
    alt: "",
    thumbnail: "Budapest/123_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/124.jpg",
    alt: "",
    thumbnail: "Budapest/124_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/125.jpg",
    alt: "",
    thumbnail: "Budapest/125_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Budapest/126.jpg",
    alt: "",
    thumbnail: "Budapest/126_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/127.jpg",
    alt: "",
    thumbnail: "Budapest/127_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/128.jpg",
    alt: "",
    thumbnail: "Budapest/128_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/129.jpg",
    alt: "",
    thumbnail: "Budapest/129_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/130.jpg",
    alt: "",
    thumbnail: "Budapest/130_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/131.jpg",
    alt: "",
    thumbnail: "Budapest/131_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/132.jpg",
    alt: "",
    thumbnail: "Budapest/132_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/133.jpg",
    alt: "",
    thumbnail: "Budapest/133_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/134.jpg",
    alt: "",
    thumbnail: "Budapest/134_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/135.jpg",
    alt: "",
    thumbnail: "Budapest/135_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/136.jpg",
    alt: "",
    thumbnail: "Budapest/136_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/137.jpg",
    alt: "",
    thumbnail: "Budapest/137_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/138.jpg",
    alt: "",
    thumbnail: "Budapest/138_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/139.jpg",
    alt: "",
    thumbnail: "Budapest/139_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/140.jpg",
    alt: "",
    thumbnail: "Budapest/140_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/141.jpg",
    alt: "",
    thumbnail: "Budapest/141_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/142.jpg",
    alt: "",
    thumbnail: "Budapest/142_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/143.jpg",
    alt: "",
    thumbnail: "Budapest/143_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/144.jpg",
    alt: "",
    thumbnail: "Budapest/144_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/145.jpg",
    alt: "",
    thumbnail: "Budapest/145_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/146.jpg",
    alt: "",
    thumbnail: "Budapest/146_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/147.jpg",
    alt: "",
    thumbnail: "Budapest/147_thumb.jpg",
    width: 1042,
    height: 1389,
  },
  {
    original: "Budapest/148.jpg",
    alt: "",
    thumbnail: "Budapest/148_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/149.jpg",
    alt: "",
    thumbnail: "Budapest/149_thumb.jpg",
    width: 9,
    height: 16,
  },
  {
    original: "Budapest/150.jpg",
    alt: "",
    thumbnail: "Budapest/150_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/151.jpg",
    alt: "",
    thumbnail: "Budapest/151_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/152.jpg",
    alt: "",
    thumbnail: "Budapest/152_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/153.jpg",
    alt: "",
    thumbnail: "Budapest/153_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/154.jpg",
    alt: "",
    thumbnail: "Budapest/154_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/155.jpg",
    alt: "",
    thumbnail: "Budapest/155_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/156.jpg",
    alt: "",
    thumbnail: "Budapest/156_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/157.jpg",
    alt: "",
    thumbnail: "Budapest/157_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/158.jpg",
    alt: "",
    thumbnail: "Budapest/158_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/159.jpg",
    alt: "",
    thumbnail: "Budapest/159_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/160.jpg",
    alt: "",
    thumbnail: "Budapest/160_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/161.jpg",
    alt: "",
    thumbnail: "Budapest/161_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/162.jpg",
    alt: "",
    thumbnail: "Budapest/162_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/163.jpg",
    alt: "",
    thumbnail: "Budapest/163_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/164.jpg",
    alt: "",
    thumbnail: "Budapest/164_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/165.jpg",
    alt: "",
    thumbnail: "Budapest/165_thumb.jpg",
    width: 1657,
    height: 562,
  },
  {
    original: "Budapest/166.jpg",
    alt: "",
    thumbnail: "Budapest/166_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Budapest/167.jpg",
    alt: "",
    thumbnail: "Budapest/167_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Budapest/168.jpg",
    alt: "",
    thumbnail: "Budapest/168_thumb.jpg",
    width: 1431,
    height: 1988,
  },
  {
    original: "Budapest/169.jpg",
    alt: "",
    thumbnail: "Budapest/169_thumb.jpg",
    width: 4,
    height: 3,
  },
];
