export const imola = [
  {
    original: "Imola/1.jpg",
    alt: "",
    thumbnail: "Imola/1_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/2.jpg",
    alt: "",
    thumbnail: "Imola/2_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/3.jpg",
    alt: "",
    thumbnail: "Imola/3_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/4.jpg",
    alt: "",
    thumbnail: "Imola/4_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/5.jpg",
    alt: "",
    thumbnail: "Imola/5_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/6.jpg",
    alt: "",
    thumbnail: "Imola/6_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/7.jpg",
    alt: "",
    thumbnail: "Imola/7_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/8.jpg",
    alt: "",
    thumbnail: "Imola/8_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/9.jpg",
    alt: "",
    thumbnail: "Imola/9_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Imola/10.jpg",
    alt: "",
    thumbnail: "Imola/10_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/11.jpg",
    alt: "",
    thumbnail: "Imola/11_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/12.jpg",
    alt: "",
    thumbnail: "Imola/12_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/13.jpg",
    alt: "",
    thumbnail: "Imola/13_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/14.jpg",
    alt: "",
    thumbnail: "Imola/14_thumb.jpg",
    width: 400,
    height: 533,
  },
  {
    original: "Imola/15.jpg",
    alt: "",
    thumbnail: "Imola/15_thumb.jpg",
    width: 1799,
    height: 1080,
  },
  {
    original: "Imola/16.jpg",
    alt: "",
    thumbnail: "Imola/16_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Imola/17.jpg",
    alt: "",
    thumbnail: "Imola/17_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/18.jpg",
    alt: "",
    thumbnail: "Imola/18_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/19.jpg",
    alt: "",
    thumbnail: "Imola/19_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Imola/20.jpg",
    alt: "",
    thumbnail: "Imola/20_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/21.jpg",
    alt: "",
    thumbnail: "Imola/21_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/22.jpg",
    alt: "",
    thumbnail: "Imola/22_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/23.jpg",
    alt: "",
    thumbnail: "Imola/23_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/24.jpg",
    alt: "",
    thumbnail: "Imola/24_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/25.jpg",
    alt: "",
    thumbnail: "Imola/25_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/26.jpg",
    alt: "",
    thumbnail: "Imola/26_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/27.jpg",
    alt: "",
    thumbnail: "Imola/27_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/28.jpg",
    alt: "",
    thumbnail: "Imola/28_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/29.jpg",
    alt: "",
    thumbnail: "Imola/29_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/30.jpg",
    alt: "",
    thumbnail: "Imola/30_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/31.jpg",
    alt: "",
    thumbnail: "Imola/31_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/32.jpg",
    alt: "",
    thumbnail: "Imola/32_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/33.jpg",
    alt: "",
    thumbnail: "Imola/33_thumb.jpg",
    width: 1799,
    height: 1080,
  },
  {
    original: "Imola/34.jpg",
    alt: "",
    thumbnail: "Imola/34_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/35.jpg",
    alt: "",
    thumbnail: "Imola/35_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/36.jpg",
    alt: "",
    thumbnail: "Imola/36_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/37.jpg",
    alt: "",
    thumbnail: "Imola/37_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/38.jpg",
    alt: "",
    thumbnail: "Imola/38_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/39.jpg",
    alt: "",
    thumbnail: "Imola/39_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/40.jpg",
    alt: "",
    thumbnail: "Imola/40_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/41.jpg",
    alt: "",
    thumbnail: "Imola/41_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/42.jpg",
    alt: "",
    thumbnail: "Imola/42_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/43.jpg",
    alt: "",
    thumbnail: "Imola/43_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/44.jpg",
    alt: "",
    thumbnail: "Imola/44_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/45.jpg",
    alt: "",
    thumbnail: "Imola/45_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/46.jpg",
    alt: "",
    thumbnail: "Imola/46_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/47.jpg",
    alt: "",
    thumbnail: "Imola/47_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/48.jpg",
    alt: "",
    thumbnail: "Imola/48_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/49.jpg",
    alt: "",
    thumbnail: "Imola/49_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/50.jpg",
    alt: "",
    thumbnail: "Imola/50_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/51.jpg",
    alt: "",
    thumbnail: "Imola/51_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/52.jpg",
    alt: "",
    thumbnail: "Imola/52_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/53.jpg",
    alt: "",
    thumbnail: "Imola/53_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/54.jpg",
    alt: "",
    thumbnail: "Imola/54_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/55.jpg",
    alt: "",
    thumbnail: "Imola/55_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/56.jpg",
    alt: "",
    thumbnail: "Imola/56_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/57.jpg",
    alt: "",
    thumbnail: "Imola/57_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/58.jpg",
    alt: "",
    thumbnail: "Imola/58_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/59.jpg",
    alt: "",
    thumbnail: "Imola/59_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/60.jpg",
    alt: "",
    thumbnail: "Imola/60_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/61.jpg",
    alt: "",
    thumbnail: "Imola/61_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/62.jpg",
    alt: "",
    thumbnail: "Imola/62_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/63.jpg",
    alt: "",
    thumbnail: "Imola/63_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/64.jpg",
    alt: "",
    thumbnail: "Imola/64_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/65.jpg",
    alt: "",
    thumbnail: "Imola/65_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/66.jpg",
    alt: "",
    thumbnail: "Imola/66_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/67.jpg",
    alt: "",
    thumbnail: "Imola/67_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/68.jpg",
    alt: "",
    thumbnail: "Imola/68_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/69.jpg",
    alt: "",
    thumbnail: "Imola/69_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/70.jpg",
    alt: "",
    thumbnail: "Imola/70_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/71.jpg",
    alt: "",
    thumbnail: "Imola/71_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/72.jpg",
    alt: "",
    thumbnail: "Imola/72_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/73.jpg",
    alt: "",
    thumbnail: "Imola/73_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/74.jpg",
    alt: "",
    thumbnail: "Imola/74_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/75.jpg",
    alt: "",
    thumbnail: "Imola/75_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/76.jpg",
    alt: "",
    thumbnail: "Imola/76_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/77.jpg",
    alt: "",
    thumbnail: "Imola/77_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/78.jpg",
    alt: "",
    thumbnail: "Imola/78_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/79.jpg",
    alt: "",
    thumbnail: "Imola/79_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/80.jpg",
    alt: "",
    thumbnail: "Imola/80_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/81.jpg",
    alt: "",
    thumbnail: "Imola/81_thumb.jpg",
    width: 1799,
    height: 1080,
  },
  {
    original: "Imola/82.jpg",
    alt: "",
    thumbnail: "Imola/82_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/83.jpg",
    alt: "",
    thumbnail: "Imola/83_thumb.jpg",
    width: 3,
    height: 4,
  },
  {
    original: "Imola/84.jpg",
    alt: "",
    thumbnail: "Imola/84_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/85.jpg",
    alt: "",
    thumbnail: "Imola/85_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/86.jpg",
    alt: "",
    thumbnail: "Imola/86_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/87.jpg",
    alt: "",
    thumbnail: "Imola/87_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/88.jpg",
    alt: "",
    thumbnail: "Imola/88_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/89.jpg",
    alt: "",
    thumbnail: "Imola/89_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/90.jpg",
    alt: "",
    thumbnail: "Imola/90_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/91.jpg",
    alt: "",
    thumbnail: "Imola/91_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/92.jpg",
    alt: "",
    thumbnail: "Imola/92_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/93.jpg",
    alt: "",
    thumbnail: "Imola/93_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/94.jpg",
    alt: "",
    thumbnail: "Imola/94_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/95.jpg",
    alt: "",
    thumbnail: "Imola/95_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/96.jpg",
    alt: "",
    thumbnail: "Imola/96_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/97.jpg",
    alt: "",
    thumbnail: "Imola/97_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/98.jpg",
    alt: "",
    thumbnail: "Imola/98_thumb.jpg",
    width: 4,
    height: 3,
  },
  {
    original: "Imola/99.jpg",
    alt: "",
    thumbnail: "Imola/99_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/100.jpg",
    alt: "",
    thumbnail: "Imola/100_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/101.jpg",
    alt: "",
    thumbnail: "Imola/101_thumb.jpg",
    width: 3,
    height: 2,
  },
  {
    original: "Imola/102.jpg",
    alt: "",
    thumbnail: "Imola/102_thumb.jpg",
    width: 16,
    height: 9,
  },
  {
    original: "Imola/103.jpg",
    alt: "",
    thumbnail: "Imola/103_thumb.jpg",
    width: 4,
    height: 3,
  },
];
