export const bruges = [
  {
    original: "Bruges/1.jpg",
    thumbnail: "Bruges/1_thumb.jpg",
    alt: "",
    width: 9,
    height: 16,
  },
  {
    original: "Bruges/2.jpg",
    thumbnail: "Bruges/2_thumb.jpg",
    alt: "",
    width: 16,
    height: 9,
  },
  {
    original: "Bruges/3.jpg",
    thumbnail: "Bruges/3_thumb.jpg",
    alt: "",
    width: 16,
    height: 9,
  },
  {
    original: "Bruges/4.jpg",
    thumbnail: "Bruges/4_thumb.jpg",
    alt: "",
    width: 4,
    height: 5,
  },
  {
    original: "Bruges/5.jpg",
    thumbnail: "Bruges/5_thumb.jpg",
    alt: "",
    width: 16,
    height: 9,
  },
  {
    original: "Bruges/6.jpg",
    thumbnail: "Bruges/6_thumb.jpg",
    alt: "",
    width: 4,
    height: 5,
  },
  {
    original: "Bruges/7.jpg",
    thumbnail: "Bruges/7_thumb.jpg",
    alt: "",
    width: 4,
    height: 5,
  },
  {
    original: "Bruges/8.jpg",
    thumbnail: "Bruges/8_thumb.jpg",
    alt: "",
    width: 16,
    height: 9,
  },
  {
    original: "Bruges/9.jpg",
    thumbnail: "Bruges/9_thumb.jpg",
    alt: "",
    width: 4,
    height: 5,
  },
  {
    original: "Bruges/10.jpg",
    thumbnail: "Bruges/10_thumb.jpg",
    alt: "",
    width: 5,
    height: 4,
  },
  {
    original: "Bruges/11.jpg",
    thumbnail: "Bruges/11_thumb.jpg",
    alt: "",
    width: 16,
    height: 9,
  },
  {
    original: "Bruges/12.jpg",
    thumbnail: "Bruges/12_thumb.jpg",
    alt: "",
    width: 16,
    height: 9,
  },
  {
    original: "Bruges/13.jpg",
    thumbnail: "Bruges/13_thumb.jpg",
    alt: "",
    width: 9,
    height: 16,
  },
  {
    original: "Bruges/14.jpg",
    thumbnail: "Bruges/14_thumb.jpg",
    alt: "",
    width: 4,
    height: 3,
  },
  {
    original: "Bruges/15.jpg",
    thumbnail: "Bruges/15_thumb.jpg",
    alt: "",
    width: 16,
    height: 9,
  },
  {
    original: "Bruges/16.jpg",
    thumbnail: "Bruges/16_thumb.jpg",
    alt: "",
    width: 5,
    height: 4,
  },
];
